# Generated by Django 4.2.7 on 2023-11-24 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neo', '0002_filetransferinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='filetransferinfo',
            name='sender_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sender Name'),
        ),
    ]
